name: CSW Trickle

on:
  schedule:
    - cron: '*/59 * * * *'
  workflow_dispatch:

concurrency:
  group: csw-sync
  cancel-in-progress: false

jobs:
  trickle:
    runs-on: ubuntu-latest

    permissions:
      # To make it work for private repos
      contents: read
    steps:
      - uses: actions/checkout@v6

      # Make sure it's at least Node v24 that supports TypeScript
      - uses: actions/setup-node@v6
        with:
         node-version: 'lts/*'

      - run: npm ci

      # Processes up to 15 pages of 100 records with 30s pauses
      # between pages. When all pending records are processed, disables
      # this workflow so it stops running until the next bulk update.
      - name: Run sync and update cursor
        run: |
          CURSOR=$(node src/sync.ts --max-pages 15)
          gh variable list
          gh variable set CSW_CURSOR --body "${CURSOR}"
          if echo "${CURSOR}" | jq -e '.pending == null' > /dev/null; then
            echo "Disable trickle workflow"
            gh workflow disable trickle.yml
          fi
        env:
          CSW_CURSOR: ${{ vars.CSW_CURSOR }}
          ATP_PDS_URL: ${{ vars.ATP_PDS_URL }}
          BLUESKY_IDENTIFIER: ${{ vars.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          GH_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB_ACTIONS }}
